workflows:
  ios-workflow:
    name: iOS App Store Build

    instance_type: mac_mini_m2

    integrations:
      app_store_connect: AppStoreUpload

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.easisoft.ianelab002

    scripts:
      - name: Setup signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release